//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BzcmText_FanChan
    {
        public BzcmText_FanChan()
        {
            this.Wx__BzcmText = new HashSet<Wx__BzcmText>();
        }
    
        public long ID { get; set; }
        public System.DateTime Addtime { get; set; }
        public int AddUser { get; set; }
        public int DEL { get; set; }
        public string Str_Name { get; set; }
        public string Str_Image { get; set; }
        public string Str_Photo { get; set; }
        public Nullable<double> IsTop { get; set; }
        public Nullable<int> IsTop_shor { get; set; }
        public Nullable<System.DateTime> IsTopStartTime { get; set; }
        public Nullable<System.DateTime> IsTopStopTime { get; set; }
        public int IsFristItemsID { get; set; }
        public string News_Name { get; set; }
        public string News_KaiFaShang { get; set; }
        public string News_Addess { get; set; }
        public Nullable<decimal> News_Money { get; set; }
        public string News_Danwei { get; set; }
        public string News_Item { get; set; }
        public string News_Photo { get; set; }
        public string News_YouHui { get; set; }
        public string News_Text { get; set; }
        public string FYXX_Name { get; set; }
        public string FYXX_Photo { get; set; }
        public string FYXX_ONE { get; set; }
        public string FYXX_TWO { get; set; }
        public string FYXX_SHRER { get; set; }
    
        public virtual IsFristItem IsFristItem { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<Wx__BzcmText> Wx__BzcmText { get; set; }
    }
}
