//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsFristItem
    {
        public IsFristItem()
        {
            this.BzcmText_FanChan = new HashSet<BzcmText_FanChan>();
        }
    
        public int ID { get; set; }
        public string Str { get; set; }
        public int Str_int { get; set; }
        public int Del { get; set; }
        public Nullable<int> Items { get; set; }
        public string Itemsstr { get; set; }
    
        public virtual ICollection<BzcmText_FanChan> BzcmText_FanChan { get; set; }
    }
}
