//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public long ID { get; set; }
        public long Uid { get; set; }
        public string GoodName { get; set; }
        public short Status { get; set; }
        public decimal GoodPrice { get; set; }
        public string AddTime { get; set; }
        public bool Del { get; set; }
    
        public virtual WXXUserInfo WXXUserInfo { get; set; }
    }
}
