//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Login_list = new HashSet<Login_list>();
            this.R_UserInfo_ActionInfo = new HashSet<R_UserInfo_ActionInfo>();
            this.Userbaks = new HashSet<Userbak>();
            this.WXXUserInfoes = new HashSet<WXXUserInfo>();
            this.Departments = new HashSet<Department>();
            this.RoleInfoes = new HashSet<RoleInfo>();
            this.BzcmText_FanChan = new HashSet<BzcmText_FanChan>();
        }
    
        public int ID { get; set; }
        public string UName { get; set; }
        public string UPwd { get; set; }
        public System.DateTime SubTime { get; set; }
        public short DelFlag { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Remark { get; set; }
        public string Sort { get; set; }
        public Nullable<System.DateTime> OverTime { get; set; }
        public Nullable<int> UserXiaoHao { get; set; }
        public Nullable<int> Click { get; set; }
        public Nullable<bool> ThisMastr { get; set; }
        public Nullable<int> MasterID { get; set; }
        public string Login_now { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<decimal> Umoney { get; set; }
        public string PerSonName { get; set; }
        public Nullable<int> QuXian { get; set; }
        public Nullable<int> BuMenID { get; set; }

        [JsonIgnore]
        public virtual BumenInfoSet BumenInfoSet { get; set; }
        [JsonIgnore]
        public virtual ICollection<Login_list> Login_list { get; set; }
        [JsonIgnore]
        public virtual ICollection<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        [JsonIgnore]
        public virtual ICollection<Userbak> Userbaks { get; set; }
        [JsonIgnore]
        public virtual ICollection<WXXUserInfo> WXXUserInfoes { get; set; }
        [JsonIgnore]
        public virtual ICollection<Department> Departments { get; set; }
        [JsonIgnore]
        public virtual ICollection<RoleInfo> RoleInfoes { get; set; }
        [JsonIgnore]
        public virtual ICollection<BzcmText_FanChan> BzcmText_FanChan { get; set; }
    }
}
